### ISSUE TITLE
find: unable to record current working directory: EDC5124I Too many open files.

### ISSUE THREAD

**Issue by ccw-1** [ZOSOpenTools/findutilsport#16]
Other platforms have lower ulimit -n, but they don't have this problem. There is no reason to keep so many fd opened.

**Comment by IgorTodorovskiIBM** [comment]
@dougburns , this is an interesting one. It's likely related to one of the patches. Let me know if you can take it on.

**Comment by IgorTodorovskiIBM** [comment]
My guess is it's related to this change: https://github.com/ZOSOpenTools/findutilsport/blob/main/patches/PR2/PR2.patch#L10

If I recall correctly, enabling the close on the file descriptor causes other issues so we probably need a more nuanced fix for this case.

**Comment by dougburns** [comment]
It isn't completely obvious why the patch you reference was added, but it looks to me like it was to try to address #4 
Now we've got the gnulib tests running, I can see that test-fdopendir fails with or without the call to "close" - with different errors.
I'm guessing if I can get fdopendir working well enough to pass the test then then issues with find are likely to be addressed as well.

**Comment by dustin-ward** [comment]
Is there any news on a potential fix for this issue? I've been running into this quite a bit recently

**Comment by IgorTodorovskiIBM** [comment]
Not yet, but we'll prioritize this - the same issue is also affecting grep since it uses the same gnulib code.

Curious, what is your open files limit?

Here's mine:
```
ulimit -a
core file size              (blocks, -c) 4096
data seg size               (kbytes, -d) unlimited
file size                   (blocks, -f) 8589934588
open files                          (-n) 64000
pipe size                (512 bytes, -p) 1
stack size                  (kbytes, -s) unlimited
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 8000
virtual memory              (kbytes, -v) unlimited
```

**Comment by dustin-ward** [comment]
This is my most restrictive machine:
```
core file size              (blocks, -c) unlimited
data seg size               (kbytes, -d) unlimited
file size                   (blocks, -f) unlimited
open files                          (-n) 1000
pipe size                (512 bytes, -p) 1
stack size                  (kbytes, -s) unlimited
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 5000
virtual memory              (kbytes, -v) unlimited
```

**Comment by IgorTodorovskiIBM** [comment]
@ccw-1 and @dustin-ward validated it, will close
